
/* ===== AUSTRALIA: "The Red Road" =====
 * It has only just begun, and the country is enormous. Kirra is a ranger who knows every waterhole. Big Pete owns a station
 * with a bore and a bad attitude. Tom keeps a locomotive alive in a shed. The road ends at a port, or at a choice.
 */
const AU={arc:'loc:australia',label:['The Red Road','הדרך האדומה'],of:6};

chapter(Object.assign({},AU,{id:'au_1',n:1,at:.06,
 t:['The Last Ordinary Week','השבוע הרגיל האחרון'],
 x:[`The town is the last place on the map where nothing has happened yet. The supermarket has queues, but the queues are polite. The radio says a virus is moving through the east coast, and the man at the pub says it will be fine by Christmas. You can feel it in the way people do not quite look at the news. A ranger named Kirra is loading her truck at the servo, and she looks at you like someone who has already decided.`,
    `העיירה היא המקום האחרון על המפה שבו עוד לא קרה כלום. בסופרמרקט יש תורים, אבל התורים מנומסים. הרדיו אומר שנגיף נע לאורך החוף המזרחי, והאיש בפאב אומר שעד חג המולד הכול יהיה בסדר. מרגישים את זה בדרך שבה אנשים לא ממש מסתכלים בחדשות. פקחית בשם קירה טוענת את המשאית שלה בתחנת הדלק, והיא מסתכלת כמי שכבר החליטה.`],
 ch:[
  {l:['Stock up and leave with Kirra','להצטייד ולעזוב עם קירה'],s:['Fuel, water, and a friend who knows the country.','דלק, מים, וחברה שמכירה את הארץ.'],check:{stat:'charisma',dc:8},
   win:[`You fill two jerry cans and a cooler, and Kirra, without a word, moves a sleeping bag to make room. The town waves you off with the wide, kind smile of people who think you are making a fuss.`,`ממלאים שני ג׳ריקנים וצידנית, וקירה, בלי מילה, מזיזה שק שינה כדי לפנות מקום. העיירה נפרדת בחיוך רחב וטוב של אנשים שחושבים שעושים מזה עניין.`,{food:3,water:3,morale:3,flag:'au_kirra'}],
   lose:[`The servo is out of fuel, and Kirra can only spare the room, not the tank. You leave with a full stomach and an empty can, and a tick in the back of your mind.`,`בתחנת הדלק נגמר הדלק, וקירה יכולה לתת רק מקום, לא מיכל. יצאת עם בטן מלאה וג׳ריקן ריק, ועם תחושה מציקה בראש.`,{food:1,morale:-3,flag:'au_kirra'}]},
  {l:['Stay a few more days and see','להישאר עוד כמה ימים ולראות'],s:['Nobody has ever regretted a slow start.','אף אחד לא התחרט על התחלה איטית.'],check:{stat:'wits',dc:9},
   win:[`You use the week: quietly buy what you need, tell three people what you have heard, and sleep well. When the news changes, you are already packed, and the town's polite queue turns into something else.`,`מנצלים את השבוע: קונים בשקט מה שצריך, מספרים לשלושה אנשים מה ששמעו, וישנים טוב. כשהחדשות משתנות, הכול כבר ארוז, והתור המנומס של העיירה הופך למשהו אחר.`,{food:3,water:2,morale:2,flag:'au_waited'}],
   lose:[`You wait a day too long. The servo is empty, the shelves are empty, and the road north is suddenly full of everyone else's headlights.`,`חיכית יום אחד יותר מדי. תחנת הדלק ריקה, המדפים ריקים, והכביש צפונה פתאום מלא בפנסים של כולם.`,{food:-1,morale:-6,hp:-2,flag:'au_waited'}]}
 ]}));

chapter(Object.assign({},AU,{id:'au_2',n:2,at:.20,
 t:["Big Pete's Station",'החווה של ביג פיט'],
 x:[()=>`Two hundred kilometres of red road, and a windmill. Big Pete's station has forty thousand acres, a water bore, a homestead with a sagging verandah, and a cattle yard that has gone strangely quiet. Pete himself is a wide, sunburnt man who sits on the steps and has decided the world is somebody else's problem. ${flag('au_kirra')?'Kirra knows him, and does not like him, and says so.':flag('au_waited')?'He looks at your car, and at the dust it has raised, and says nothing for a long minute.':'He looks up from his tea.'} He says there is a bunkhouse, and there is work.`,
    ()=>`מאתיים קילומטר של כביש אדום, וטחנת רוח. לחווה של ביג פיט ארבעים אלף אקר, באר מים, בית עם מרפסת שוקעת, וחצר בקר שנעשתה שקטה באופן מוזר. פיט עצמו איש רחב ושזוף שיושב על המדרגות והחליט שהעולם בעיה של מישהו אחר. ${flag('au_kirra')?'קירה מכירה אותו, ולא אוהבת אותו, ואומרת את זה.':flag('au_waited')?'הוא מסתכל על הרכב, ועל האבק שהוא הרים, ולא אומר דבר דקה ארוכה.':'הוא מרים מבט מהתה.'} הוא אומר שיש בית פועלים, ויש עבודה.`],
 ch:[
  {l:['Take the bunkhouse and work','לקחת את בית הפועלים ולעבוד'],s:['Fence, bore and cattle.','גדר, באר ובקר.'],check:{stat:'stamina',dc:10},
   win:[`You mend a kilometre of fence, muster forty head, and grease a windmill in a wind that tastes like iron. Pete does not thank you, but he leaves a plate of tea and damper on the bunkhouse table, every night.`,`מתקנים קילומטר גדר, מקבצים ארבעים ראשי בקר, ומשמנים טחנת רוח ברוח בטעם ברזל. פיט לא מודה, אבל משאיר צלחת תה ולחם על שולחן בית הפועלים, בכל לילה.`,{food:3,water:2,morale:4,hp:2,flag:'au_station'}],
   lose:[`The heat gets you on the second day. You spend the afternoon in the shade with a wet shirt on your head, and Pete brings you water without a word, and without looking.`,`החום תופס אותך ביום השני. בילית את אחר הצהריים בצל עם חולצה רטובה על הראש, ופיט מביא מים בלי מילה, ובלי להסתכל.`,{hp:-6,morale:-3,flag:'au_station'}]},
  {l:['Trade for water and move on','לסחור על מים ולהמשיך'],s:['The bore is his, the road is yours.','הבאר שלו, הדרך שלך.'],check:{stat:'charisma',dc:9},
   win:[`Pete drives a hard bargain and a harder truck. You leave with three full jerry cans, a hat that is too big, and a rumour about a rail line to the north.`,`פיט מתמקח קשה ונוהג קשה יותר. יצאת עם שלושה ג׳ריקנים מלאים, כובע גדול מדי, ושמועה על קו רכבת בצפון.`,{water:4,morale:2,flag:['au_trade','au_rumor']}],
   lose:[`Pete wants more than you have, and shrugs when you offer less. You leave with a single can, and the dust of his truck in your mouth.`,`פיט רוצה יותר ממה שיש, ומושך בכתפיים כשמציעים פחות. יצאת עם ג׳ריקן אחד, ועם אבק המשאית שלו בפה.`,{water:1,morale:-4,flag:'au_trade'}]}
 ]}));

chapter(Object.assign({},AU,{id:'au_3',n:3,at:.36,
 t:['The Ranger','הפקחית'],
 x:[()=>`Kirra knows the waterholes the way other people know their phone numbers. She draws them on the map in pencil: a soak, a rock hole, a windmill on a lease that has not paid rates since 1987. She says the country is going to feel very big and very small at the same time, and that the only thing that matters is where the next drink is. ${flag('au_kirra')?'She has driven with you for a week, and has not yet told you where she is really going.':'You met her at the servo, briefly, and you have seen her twice since, at a distance.'}`,
    ()=>`קירה מכירה את מקווי המים כמו שאחרים מכירים מספרי טלפון. היא מציירת אותם על המפה בעיפרון: מעיין חול, בור סלע, טחנת רוח בחכירה שלא שילמה ארנונה מ־1987. היא אומרת שהארץ תרגיש גדולה מאוד וקטנה מאוד בו בזמן, ושהדבר היחיד שחשוב הוא איפה השתייה הבאה. ${flag('au_kirra')?'היא נוסעת איתך שבוע, ועדיין לא סיפרה לאן היא באמת הולכת.':'נפגשתם בתחנת הדלק, בקצרה, וראיתם אותה פעמיים מאז, מרחוק.'}`],
 ch:[
  {l:['Follow her route','ללכת אחרי המסלול שלה'],s:['She has never lost a person in the desert.','היא מעולם לא איבדה אדם במדבר.'],check:{stat:'stamina',dc:10},
   win:[`Five days of red dust, dry creek beds and a sky the size of a country. Every waterhole is where she said it would be. On the fifth night she tells you where she is really going, and it is somewhere you would like to go.`,`חמישה ימים של אבק אדום, נחלים יבשים ושמיים בגודל של מדינה. כל מקווה מים נמצא איפה שאמרה. בלילה החמישי היא מספרת לאן היא באמת הולכת, וזה מקום שרוצים ללכת אליו.`,{water:3,morale:6,humanity:2,flag:'au_followed'}],
   lose:[`The second waterhole is dry, and the third is muddy. Kirra shrugs, and says the country is like that, and you drink boiled water and watch the horizon.`,`מקווה המים השני יבש, והשלישי בוצי. קירה מושכת בכתפיים ואומרת שהארץ היא כזאת, ושותים מים מבושלים ומסתכלים באופק.`,{hp:-8,water:-2,morale:-4,flag:'au_followed'}]},
  {l:['Map your own route','למפות מסלול משלך'],s:['A map is a promise, and promises break.','מפה היא הבטחה, והבטחות נשברות.'],check:{stat:'wits',dc:11},
   win:[`You cross-reference her pencil marks with an old atlas and an older feeling. The route you draw is longer, and stranger, and gets you there a day earlier than hers.`,`משווים את סימני העיפרון שלה לאטלס ישן ולתחושה ישנה יותר. המסלול שמציירים ארוך יותר, מוזר יותר, ומגיע יום מוקדם משלה.`,{water:2,morale:3,flag:'au_own'}],
   lose:[`Your route crosses a salt lake that is not on the atlas. It costs you a tyre, a day, and most of a bottle of patience.`,`המסלול חוצה אגם מלח שלא מופיע באטלס. זה עולה בצמיג, ביום, וברוב בקבוק של סבלנות.`,{water:-2,hp:-4,morale:-4,flag:'au_own'}]}
 ]}));

chapter(Object.assign({},AU,{id:'au_4',n:4,at:.52,
 t:['The Dry','היובש'],
 x:[()=>`The bore fails at noon on the twelfth day: a cough, a rattle, and then nothing but the sound of red dust settling in the tank. There are thirty people in the camp by now, in a scatter of tents around a windmill. Someone says the water table has dropped. Someone else says it is a pump. ${flag('au_station')?'Pete stands with his hat in his hands, for the first time looking his age.':flag('au_followed')?'Kirra kneels by the tank and says she knows where a second bore is, three hours west.':'Everyone looks at the empty tank, and then at you.'}`,
    ()=>`הבאר נכשלת בצהריים ביום השנים עשר: שיעול, רעש, ואז רק קול האבק האדום שנוחת במיכל. יש עכשיו שלושים איש במחנה, בפיזור אוהלים סביב טחנת רוח. מישהו אומר שמפלס המים ירד. מישהו אחר אומר שזו משאבה. ${flag('au_station')?'פיט עומד עם הכובע בידיים, ובפעם הראשונה נראה בגילו.':flag('au_followed')?'קירה כורעת ליד המיכל ואומרת שהיא יודעת איפה יש באר שנייה, שלוש שעות מערבה.':'כולם מסתכלים במיכל הריק, ואחר כך עליך.'}`],
 ch:[
  {l:['Dig for water','לחפור אחרי מים'],s:['The old well is still there, under the sand.','הבאר הישנה עדיין שם, מתחת לחול.'],check:{stat:'strength',dc:11},
   win:[`Eight hours in a hole, and the sand goes dark. It is a seep at first, then a trickle, then a real shine at the bottom of the shaft. The camp cheers with cracked lips, and Pete gives you his hat.`,`שמונה שעות בבור, והחול מחשיך. בהתחלה חלחול, אחר כך טפטוף, ואז ברק אמיתי בתחתית הפיר. המחנה מריע בשפתיים סדוקות, ופיט נותן את הכובע שלו.`,{water:5,hp:-6,morale:6,flag:'au_dug'}],
   lose:[`You hit rock at three metres and a gas that makes your head sing. You climb out on a rope, sick and empty-handed, and the camp is very quiet.`,`פוגעים בסלע בשלושה מטרים ובגז שגורם לראש לשיר. מטפסים החוצה על חבל, חולים וידיים ריקות, והמחנה שקט מאוד.`,{hp:-10,inf:3,morale:-6,flag:'au_dug'}]},
  {l:['Haul water from the second bore','להוביל מים מהבאר השנייה'],s:['Three hours west, and back.','שלוש שעות מערבה, וחזרה.'],check:{stat:'stamina',dc:10,mod:()=>flag('au_followed')?2:0},
   win:[`Six trips, four hundred litres, and a truck that sounds like it is dying. The second bore is where Kirra said, and it is deep and cold and sweet. The camp drinks, and no one says anything, because there is nothing to say.`,`שש נסיעות, ארבע מאות ליטר, ומשאית שנשמעת כמו גוססת. הבאר השנייה היא איפה שקירה אמרה, עמוקה וקרה ומתוקה. המחנה שותה, ואיש לא אומר דבר, כי אין מה לומר.`,{water:4,hp:-4,morale:4,flag:'au_hauled'}],
   lose:[`The truck stalls at the second trip, and you walk back with a jerry can in each hand. It is enough for a day. It will have to be enough for two.`,`המשאית נתקעת בנסיעה השנייה, וחוזרים ברגל עם ג׳ריקן בכל יד. זה מספיק ליום. זה יצטרך להספיק לשניים.`,{water:1,hp:-8,morale:-5,flag:'au_hauled'}]}
 ]}));

chapter(Object.assign({},AU,{id:'au_5',n:5,at:.70,
 t:['The Rail','המסילה'],
 x:[()=>`A freight line runs north across the flat country, to a port that still has ships. Tom, the railman, has kept a locomotive alive in a shed at the siding for twenty years, out of habit and stubbornness. He says it will run, if someone can get the boiler pressure right and the fuel right and a few hundred metres of bad track. ${flag('au_rumor')?'The rumour Pete gave you turns out to be true.':'The rail is a rumour that is also a fact.'} The camp looks at the locomotive, and at the horizon.`,
    ()=>`קו רכבת משא עובר צפונה על פני הארץ השטוחה, אל נמל שעדיין יש בו ספינות. טום, איש הרכבת, שמר על קטר חי בסככה בצד המסילה עשרים שנה, מתוך הרגל ועקשנות. הוא אומר שהוא ירוץ, אם מישהו יצליח לתקן את לחץ הדוד ואת הדלק ואת כמה מאות מטרים של מסילה גרועה. ${flag('au_rumor')?'השמועה שפיט נתן התבררה כנכונה.':'המסילה היא שמועה שהיא גם עובדה.'} המחנה מסתכל בקטר, ובאופק.`],
 ch:[
  {l:['Get the engine running','להניע את הקטר'],s:['Twenty years of dust and one good idea.','עשרים שנה של אבק ורעיון טוב אחד.'],check:{stat:'wits',dc:11,bg:{mechanic:2}},
   win:[`Steam, grease and a whistle that startles a flock of galahs. Tom dances a very small jig on the footplate, and the locomotive takes a long breath and rolls out of the shed, one wheel at a time.`,`קיטור, שומן וצפירה שמבהילה להקת תוכים. טום רוקד ג׳יג קטן מאוד על הרציף, והקטר נושם נשימה ארוכה ויוצא מהסככה, גלגל אחר גלגל.`,{order:3,morale:8,flag:'au_train'}],
   lose:[`The boiler leaks, the fuel is thick, and the whistle gives only a sad half-note. Tom pats the locomotive like a horse that has let him down, and it takes another two days to try again.`,`הדוד דולף, הדלק סמיך, והצפירה נותנת רק חצי צליל עצוב. טום טופח על הקטר כמו על סוס שאכזב אותו, ועוברים עוד יומיים עד לניסיון הבא.`,{morale:-5,hp:-3,flag:'au_train'}]},
  {l:['Ride the freight cars','לנסוע על קרונות המשא'],s:['A freight car is a bed that goes somewhere.','קרון משא הוא מיטה שנוסעת לאנשהו.'],check:{stat:'stealth',dc:10},
   win:[`You climb into an empty box car and slide the door to a crack. The country rolls past, red and flat and wide, and you sleep for the first time in a week with the sound of steel on steel.`,`מטפסים לקרון משא ריק ומסיטים את הדלת לסדק. הארץ מתגלגלת בחוץ, אדומה ושטוחה ורחבה, וישנים בפעם הראשונה בשבוע לקול פלדה על פלדה.`,{morale:5,hp:3,flag:'au_freight'}],
   lose:[`The car is not empty. It is full of something that is not quite asleep, and you leave by the other door at a speed the door was not built for.`,`הקרון לא ריק. הוא מלא במשהו שלא ממש ישן, ויוצאים דרך הדלת השנייה במהירות שהדלת לא נבנתה לה.`,{hp:-10,inf:6,morale:-4,flag:'au_freight'}]}
 ]}));

chapter(Object.assign({},AU,{id:'au_6',n:6,at:.88,
 t:['The Port','הנמל'],
 x:[()=>`The port is a low city of containers and cranes, and at the end of the longest pier a ship is taking on people. A woman with a megaphone says there is room for two hundred, and that the list closes at dawn. ${flag('au_train')?'The locomotive whistle has brought the town out to watch you arrive.':flag('au_freight')?'You come in the way freight does, quietly, and every eye at the gate is on you.':'You arrive on foot, dusty, with half a dozen others.'} Behind you, the country. Ahead, the sea, and a decision that has been in the road since the servo.`,
    ()=>`הנמל הוא עיר נמוכה של מכולות ועגורנים, ובקצה המזח הארוך ביותר ספינה מעלה אנשים. אישה עם מגפון אומרת שיש מקום למאתיים, ושהרשימה נסגרת עם עלות השחר. ${flag('au_train')?'צפירת הקטר הוציאה את העיירה לראות את ההגעה.':flag('au_freight')?'מגיעים כמו שמשא מגיע, בשקט, וכל עין בשער עליכם.':'מגיעים ברגל, מאובקים, עם חצי תריסר אחרים.'} מאחור, הארץ. מלפנים, הים, והחלטה שנמצאת בדרך מאז תחנת הדלק.`],
 ch:[
  {l:['Board the ship','לעלות על הספינה'],s:['A long sea, and a chance at something else.','ים ארוך, וסיכוי לדבר אחר.'],check:{stat:'charisma',dc:10,mod:()=>flag('au_train')?2:0},
   win:[`The gangplank is narrow and the crowd is patient. Your name is on the list, and so are half the people you rode with, and when the ship leaves the wharf the whole deck sings a song nobody can remember learning.`,`הגשר צר וההמון סבלני. השם ברשימה, וגם חצי מהאנשים שנסעו ביחד, וכשהספינה עוזבת את המזח כל הסיפון שר שיר שאיש לא זוכר שלמד.`,{morale:9,order:3,humanity:2,flag:'au_end_ship'}],
   lose:[`The list closes as you reach the gate. A woman with a clipboard says she is sorry, and means it. You spend the night on the wharf with the sea a black shape beyond the rail.`,`הרשימה נסגרת כשמגיעים לשער. אישה עם לוח כתיבה אומרת שהיא מצטערת, ומתכוונת לזה. בילית את הלילה על המזח עם הים צורה שחורה מעבר לגדר.`,{hp:-4,morale:-6,flag:'au_missed'}]},
  {l:['Stay in the country and build','להישאר בארץ ולבנות'],s:['The red road is not empty. It is only quiet.','הדרך האדומה אינה ריקה. היא רק שקטה.'],check:{stat:'strength',dc:10,mod:()=>(flag('au_dug')||flag('au_hauled'))?1:0},
   win:[`You turn the truck around, and half the camp turns with you. By winter the station has a garden, a school and a rail schedule, and Pete has hung a sign at the gate that says WELCOME in letters four feet tall.`,`מסובבים את המשאית, וחצי מהמחנה מסתובב איתה. עד החורף יש לחווה גינה, בית ספר ולוח זמנים של רכבת, ופיט תלה בשער שלט שאומר WELCOME באותיות בגובה מטר.`,{order:5,humanity:5,morale:6,flag:['au_end_stay','builder']}],
   lose:[`The country is bigger than a plan. You stay, and it is hard, and the first winter takes more than you had. But the station holds, and the light in its window is on.`,`הארץ גדולה מתוכנית. נשארים, וזה קשה, והחורף הראשון לוקח יותר ממה שהיה. אבל החווה מחזיקה, והאור בחלון שלה דולק.`,{order:1,morale:-3,humanity:3,flag:'au_end_stay'}]}
 ]}));
