
/* ---------- every companion has a story. supporting them deepens the bond; the hard road costs trust. ---------- */
const inSquad=n=>G.p.group.find(m=>m.name===n);
function story(o){
  const bond='bond_'+o.n;
  defEv({id:'cs_'+o.n,cond:()=>{const m=inSquad(o.n);return !!m&&G.w.day-(m.since||0)>=T(3);},w:26,
   t:o.t,x:o.x,
   ch:[
    {l:o.A.l,s:o.A.s,check:{p:.65},
     win:[o.A.w[0],o.A.w[1],Object.assign({morale:6,loy:{[o.n]:2},flag:bond},o.A.wx||{})],
     lose:[o.A.f[0],o.A.f[1],Object.assign({morale:-3,loy:{[o.n]:-1}},o.A.lx||{})]},
    {l:o.B.l,s:o.B.s,check:{p:.55},
     win:[o.B.w[0],o.B.w[1],Object.assign({loy:{[o.n]:-1}},o.B.wx||{})],
     lose:[o.B.f[0],o.B.f[1],Object.assign({morale:-5,loy:{[o.n]:-2}},o.B.lx||{})]}
   ]});
}
story({n:'Tiago',t:['The Key Ring','טבעת המפתחות'],
 x:[`Tiago never lets his brass key ring out of reach. Tonight he tells you why: each key opened a door in a building that no longer stands. He asks if you would walk with him to the last one.`,`טיאגו לא מרפה מטבעת המפתחות הנחושת שלו. הלילה הוא מספר למה: כל מפתח פתח דלת בבניין שכבר לא קיים. הוא שואל אם אפשר ללכת איתו אל האחרון.`],
 A:{l:['Walk with him','ללכת איתו'],s:['Some doors are worth visiting.','יש דלתות ששווה לבקר.'],w:[`The last building is a burnt shell, but the key still turns in the lock. Inside: a photograph nobody took. He cries. You stand guard.`,`הבניין האחרון הוא שלד שרוף, אבל המפתח עדיין מסתובב במנעול. בפנים: תצלום שאיש לא צילם. הוא בוכה. עמדת על המשמר.`],f:[`The building isn't empty.`,`הבניין לא ריק.`],lx:{hp:-10}},
 B:{l:['Tell him they are only keys','להגיד לו שאלה רק מפתחות'],s:['Gentle, or just practical.','עדין, או פשוט מעשי.'],w:[`He nods slowly and hands you the ring. A market trader gives you a can of beans for the brass.`,`הוא מהנהן לאט ומוסר לך את הטבעת. סוחר בשוק נותן שימור שעועית תמורת הנחושת.`],wx:{food:2},f:[`He doesn't speak to you for two days.`,`הוא לא מדבר איתך יומיים.`]}});
story({n:'Lucia',t:['The Song','השיר'],
 x:[`Lucia hasn't sung since the blackout. Tonight she hums something from your childhood, stops, and asks if you remember the words.`,`לוסיה לא שרה מאז הפסקת החשמל. הלילה היא מזמזמת משהו מהילדות, נעצרת, ושואלת אם המילים נשארו בזיכרון.`],
 A:{l:['Sing it with her','לשיר איתה'],s:['Even if you get it wrong.','גם אם טועים.'],w:[`You get the second verse wrong, and she laughs for the first time in weeks.`,`טעית בבית השני, והיא צוחקת לראשונה מזה שבועות.`],f:[`Your voices carry. Something answers from the dark.`,`הקולות נושאים. משהו עונה מהחושך.`],lx:{hp:-8}},
 B:{l:['Tell her to keep quiet','להגיד לה לשתוק'],s:['Harsh, and safe.','קשוח, ובטוח.'],w:[`She nods, and the night stays silent.`,`היא מהנהנת, והלילה נשאר שקט.`],wx:{hp:5},f:[`She cries, and you can't take it back.`,`היא בוכה, ואי אפשר לקחת את זה בחזרה.`]}});
story({n:'Haruto',t:['The Finish Line','קו הסיום'],
 x:[`Haruto runs the same loop every dawn. This morning he asks you to time him. He says he was training for a race that will never be held.`,`הארוטו רץ את אותו מסלול בכל שחר. הבוקר הוא מבקש למדוד לו זמן. הוא אומר שהתאמן למרוץ שלעולם לא ייערך.`],
 A:{l:['Time him, and run the last lap with him','למדוד זמן ולרוץ איתו את ההקפה האחרונה'],s:['Everyone needs a finish line.','כולם צריכים קו סיום.'],w:[`He crosses an imaginary line, arms raised, and you both laugh until you can't breathe.`,`הוא חוצה קו דמיוני, ידיים באוויר, ושניכם צוחקים עד שאי אפשר לנשום.`],f:[`Halfway through, the loop leads past something you'd rather not have seen.`,`באמצע, המסלול עובר ליד משהו שעדיף היה לא לראות.`],lx:{morale:-6}},
 B:{l:['Tell him to save his strength','להגיד לו לחסוך כוחות'],s:['Practical, and a little cold.','מעשי, וקצת קר.'],w:[`He shrugs and hands you the stopwatch. You use it to time the watch shifts.`,`הוא מושך בכתפיים ומוסר לך את שעון העצר. משתמשים בו למדידת משמרות.`],wx:{hp:3},f:[`He runs anyway and comes back with a sprained ankle.`,`הוא רץ בכל זאת וחוזר עם קרסול נקוע.`]}});
story({n:'Amira',t:['What She Carried','מה שנשאה'],
 x:[`Amira keeps a small tin box close. Tonight she opens it: three photographs, a stethoscope, and a letter she cannot read aloud. She asks if someone would read it to her.`,`אמירה שומרת קופסת פח קטנה קרובה אליה. הלילה היא פותחת אותה: שלושה תצלומים, סטטוסקופ ומכתב שאינה מסוגלת לקרוא בקול. היא שואלת אם מישהו יקרא לה אותו.`],
 A:{l:['Read the letter aloud','לקרוא את המכתב בקול'],s:['Some words need a voice.','יש מילים שצריכות קול.'],w:[`It is a short letter, and the last line is a recipe. She laughs until she weeps.`,`זה מכתב קצר, ושורתו האחרונה היא מתכון. היא צוחקת עד שהיא בוכה.`],f:[`It is in a language you can't read, and you butcher every word. She forgives you.`,`הוא בשפה שאי אפשר לקרוא, והשגיאות בכל מילה. היא סולחת.`],lx:{morale:-2}},
 B:{l:['Say some things stay private','להגיד שיש דברים שנשארים פרטיים'],s:['Respect is also a kindness.','כבוד הוא גם טוב לב.'],w:[`She closes the box and thanks you. It is a quiet night.`,`היא סוגרת את הקופסה ומודה. זה לילה שקט.`],wx:{meds:1},f:[`She takes it as coldness.`,`היא מבינה את זה כקור.`]}});
story({n:'Yael',t:['The Bandage Roll','גליל התחבושות'],
 x:[`Yael counts her bandages every night, like a prayer. Tonight she is one short. She doesn't accuse anyone; she only looks at the floor.`,`יעל סופרת את התחבושות שלה בכל לילה, כמו תפילה. הלילה חסרה אחת. היא לא מאשימה אף אחד; רק מסתכלת על הרצפה.`],
 A:{l:['Search the camp with her','לחפש איתה במחנה'],s:['Quietly, and together.','בשקט, ויחד.'],w:[`You find it under a sleeping child's arm, wrapped around a scraped knee. Yael says nothing, and sits with the child until morning.`,`מוצאים אותה מתחת לזרוע של ילד ישן, כרוכה סביב ברך שרוטה. יעל לא אומרת דבר, ויושבת עם הילד עד הבוקר.`],f:[`The search wakes the whole camp.`,`החיפוש מעיר את כל המחנה.`],lx:{morale:-4}},
 B:{l:['Let it go and count again','לוותר ולספור שוב'],s:['Small things go missing.','דברים קטנים נעלמים.'],w:[`She counts twice, sighs, and the bandage turns up in the morning.`,`היא סופרת פעמיים, נאנחת, והתחבושת מופיעה בבוקר.`],wx:{morale:2},f:[`Small things go missing, and a camp learns to notice.`,`דברים קטנים נעלמים, ומחנה לומד לשים לב.`]}});
story({n:'Ruth',t:['Forty Years','ארבעים שנה'],
 x:[`Ruth says that in forty years as a paramedic she never lost a patient she couldn't name. She is naming them now, quietly, one by one, and asks you to stay awake with her.`,`רות אומרת שבארבעים שנה כפרמדיקית מעולם לא איבדה מטופל שלא זכרה בשמו. היא מנקדת אותם עכשיו, בשקט, אחד אחד, ומבקשת שיישארו ערים איתה.`],
 A:{l:['Stay and listen','להישאר ולהקשיב'],s:['Forty names before dawn.','ארבעים שמות לפני עלות השחר.'],w:[`You hear all forty before dawn. She squeezes your hand at the last one.`,`שמעת את כל הארבעים לפני עלות השחר. היא לוחצת את היד באחרון.`],f:[`By the twentieth name, your eyes close, and she notices.`,`עד השם העשרים העיניים נעצמות, והיא שמה לב.`],lx:{morale:-4}},
 B:{l:['Suggest she sleeps','להציע לה לישון'],s:['Gently, and firmly.','בעדינות, ובנחישות.'],w:[`She sleeps deeply for the first time in days, and wakes rested enough to patch up your bruises.`,`היא ישנה עמוק לראשונה מזה ימים, ומתעוררת רעננה מספיק כדי לחבוש חבורות.`],wx:{hp:6},f:[`She says she'll sleep when the dead do.`,`היא אומרת שתישן כשהמתים יישנו.`]}});
story({n:'Aiko',t:['The Storeroom Key','מפתח המחסן'],
 x:[`Aiko still carries the store's storeroom key and keeps polishing it. She says she never got to lock up on the last day. She asks if someone would help her find the shop and lock it properly.`,`אייקו עדיין נושאת את מפתח המחסן של החנות וממשיכה לצחצח אותו. היא אומרת שלא הספיקה לנעול ביום האחרון. היא שואלת אם מישהו יעזור לה למצוא את החנות ולנעול אותה כמו שצריך.`],
 A:{l:['Go back and lock the shop','לחזור ולנעול את החנות'],s:['A small ritual, done properly.','טקס קטן, כמו שצריך.'],w:[`The shop is silent, the shelves half bare. She locks the door, bows, and gives you what is left in the drawer: three cans of peaches.`,`החנות שקטה, המדפים חצי ריקים. היא נועלת את הדלת, משתחווה ונותנת מה שנשאר במגירה: שלושה שימורי אפרסק.`],wx:{food:3},f:[`Someone is already inside.`,`מישהו כבר בפנים.`],lx:{hp:-10}},
 B:{l:['Tell her the key doesn\'t matter now','להגיד לה שהמפתח כבר לא משנה'],s:['True, and hard.','נכון, וקשה.'],w:[`She stops polishing it. She hangs it around your neck and says: then it's yours to carry.`,`היא מפסיקה לצחצח. היא תולה אותו על צווארך ואומרת: אז זה שלך לשאת.`],wx:{morale:3},f:[`She folds into herself for a week.`,`היא מקופלת בתוך עצמה שבוע.`]}});
story({n:'Sami',t:['The Empty Chair','הכיסא הריק'],
 x:[`Sami saves a seat at every meal, one empty spot by the fire. Nobody asks who it's for. Tonight he asks if someone would say something about them.`,`סאמי שומר מקום בכל ארוחה, מקום ריק ליד האש. אף אחד לא שואל למי. הלילה הוא מבקש שמישהו יגיד משהו עליהם.`],
 A:{l:['Say a few words','להגיד כמה מילים'],s:['Whatever comes.','מה שיבוא.'],w:[`You say what you can. He nods, and sits down in the chair himself.`,`אמרת מה שיכולת. הוא מהנהן, ויושב בעצמו בכיסא.`],f:[`You get it wrong, and he leaves the fire.`,`טעית, והוא עוזב את האש.`],lx:{morale:-4}},
 B:{l:['Move the chair to make room','להזיז את הכיסא כדי לפנות מקום'],s:['Hard, and honest.','קשה, ואמיתי.'],w:[`He stares at you, then moves it himself. Something has changed.`,`הוא בוהה בך, ואז מזיז אותו בעצמו. משהו השתנה.`],wx:{morale:3},f:[`He doesn't speak for days.`,`הוא לא מדבר ימים.`]}});
story({n:'Nora',t:['The Van','הוואן'],
 x:[`Nora talks to her van as if it were a horse. Tonight it won't start. She says it isn't the engine: it just doesn't want to go where the road goes.`,`נורה מדברת אל הוואן שלה כאילו היה סוס. הלילה הוא לא מתניע. היא אומרת שזה לא המנוע: הוא פשוט לא רוצה ללכת לאן שהדרך הולכת.`],
 A:{l:['Sit with her and try again','לשבת איתה ולנסות שוב'],s:['Patience, and a long night.','סבלנות, ולילה ארוך.'],w:[`At dawn, the van coughs, sputters, and starts. She kisses the dashboard.`,`עם עלות השחר הוואן משתעל, מפרפר ומתניע. היא מנשקת את לוח המחוונים.`],f:[`The morning brings no luck and no fuel.`,`הבוקר לא מביא מזל ולא דלק.`],lx:{food:-1}},
 B:{l:['Suggest leaving the van behind','להציע להשאיר את הוואן'],s:['Move on, lighter.','להמשיך, קל יותר.'],w:[`She sighs, empties it, and keeps the license plate. The road gets shorter.`,`היא נאנחת, מרוקנת אותו ושומרת את לוחית הרישוי. הדרך מתקצרת.`],wx:{food:2},f:[`She refuses, and rides in silence for a week.`,`היא מסרבת, ונוסעת בשתיקה שבוע.`]}});
story({n:'Dona Marta',t:['The Recipe','המתכון'],
 x:[`Dona Marta cooks for everyone but never eats when others watch. Tonight you see why: she is stretching her own portion into everyone else's. She asks you not to tell.`,`דונה מרתה מבשלת לכולם אבל אף פעם לא אוכלת כשאחרים צופים. הלילה רואים למה: היא מותחת את המנה שלה לתוך המנות של כולם. היא מבקשת לא לספר.`],
 A:{l:['Insist that she eats','לעמוד על כך שתאכל'],s:['Gently, and not taking no.','בעדינות, ובלי לקבל לא.'],w:[`She eats, grumbling, and the stew has never tasted better.`,`היא אוכלת, מתלוננת, והתבשיל מעולם לא היה טעים יותר.`],f:[`She refuses, and the stew goes cold between you.`,`היא מסרבת, והתבשיל מתקרר ביניכם.`],lx:{morale:-3}},
 B:{l:['Say nothing','לא להגיד דבר'],s:['The camp eats better for it.','המחנה אוכל טוב יותר בגללה.'],w:[`You say nothing, and she smiles into the pot.`,`לא אמרת דבר, והיא מחייכת לתוך הסיר.`],wx:{food:2},f:[`Someone else sees, and says something worse.`,`מישהו אחר רואה, ואומר משהו גרוע יותר.`]}});
story({n:'Mara',t:['The Map in the Dirt','המפה באדמה'],
 x:[`Mara draws routes in the dirt without looking at them. Tonight she draws one that ends in a circle. She says it's a place she used to go when she was young, and she is afraid to go back.`,`מארה מציירת מסלולים באדמה בלי להסתכל עליהם. הלילה היא מציירת אחד שנגמר בעיגול. היא אומרת שזה מקום שהייתה הולכת אליו כשהייתה צעירה, והיא מפחדת לחזור.`],
 A:{l:['Offer to go with her','להציע ללכת איתה'],s:['Some places need company.','יש מקומות שצריכים חברה.'],w:[`The place is a hill with a bench, empty. She sits, and for the first time tells you her real name.`,`המקום הוא גבעה עם ספסל, ריקה. היא יושבת, ולראשונה מספרת לך את שמה האמיתי.`],f:[`The hill is not empty.`,`הגבעה לא ריקה.`],lx:{hp:-10}},
 B:{l:['Choose a route that avoids it','לבחור מסלול שעוקף אותו'],s:['Some places should stay away.','יש מקומות שכדאי להישאר מהם רחוק.'],w:[`She looks relieved, and draws another.`,`היא נראית מוקלת, ומציירת אחר.`],wx:{water:2},f:[`She goes anyway, alone, and comes back two days later, silent.`,`היא הולכת בכל זאת, לבד, וחוזרת יומיים אחר כך, שותקת.`]}});
story({n:'Dev',t:['The Radio Parts','חלקי הרדיו'],
 x:[`Dev has been stripping radios for parts, building something in secret. Tonight he finally shows it: a transmitter the size of a lunchbox. He asks if someone would trust him to use it.`,`דב מפרק רדיואים לחלקים, בונה משהו בסתר. הלילה הוא סוף סוף מראה אותו: משדר בגודל קופסת אוכל. הוא שואל אם מישהו יסמוך עליו להשתמש בו.`],
 A:{l:['Let him broadcast','לתת לו לשדר'],s:['A voice into the dark.','קול אל החושך.'],w:[`For an hour a voice from the dead world says: we are alive. Somewhere, a voice answers.`,`במשך שעה קול מהעולם המת אומר: אנחנו חיים. איפשהו, קול עונה.`],wx:{morale:6},f:[`The signal draws attention, but not the good kind.`,`האות מושך תשומת לב, אבל לא מהסוג הטוב.`],lx:{hp:-10,outbreak:2}},
 B:{l:['Tell him to keep it hidden','להגיד לו להסתיר אותו'],s:['Quiet is safe.','שקט הוא בטוח.'],w:[`He nods, and hands you a fresh battery.`,`הוא מהנהן, ומוסר לך סוללה טרייה.`],wx:{ammo:1},f:[`He sulks, and stops fixing things.`,`הוא מתעצבן, ומפסיק לתקן דברים.`]}});
story({n:'Ms. Cole',t:['The Roll Call','קריאת השמות'],
 x:[`Every morning, Ms. Cole reads a list of names aloud. They are her students. Most of them are gone. Today she asks if someone would read the list with her.`,`בכל בוקר גב׳ קול מקריאה רשימת שמות בקול. אלה התלמידים שלה. רובם איננו. היום היא שואלת אם מישהו יקרא איתה את הרשימה.`],
 A:{l:['Read it with her','לקרוא איתה'],s:['Forty-one names.','ארבעים ואחד שמות.'],w:[`Forty-one names. You pause after each. By the end, the whole camp is standing.`,`ארבעים ואחד שמות. עוצרים אחרי כל אחד. עד הסוף כל המחנה עומד.`],f:[`You stumble on a name, and she goes very still.`,`מועדים על שם, והיא נעשית דוממת מאוד.`],lx:{morale:-4}},
 B:{l:['Suggest she skip the list','להציע לה לדלג על הרשימה'],s:['Some mornings are too heavy.','יש בקרים כבדים מדי.'],w:[`She nods, and folds the list away. The mornings get easier.`,`היא מהנהנת ומקפלת את הרשימה. הבקרים נעשים קלים יותר.`],wx:{morale:4},f:[`She leaves the room, and the day begins without her.`,`היא עוזבת את החדר, והיום מתחיל בלעדיה.`]}});
story({n:'Cpl. Reyes',t:['The Rifle','הרובה'],
 x:[`Reyes cleans his rifle every night, though he hasn't fired it in weeks. Tonight he asks if someone would hold it and say they trust him with it.`,`ריאס מנקה את הרובה שלו כל לילה, למרות שלא ירה בו שבועות. הלילה הוא שואל אם מישהו יחזיק אותו ויגיד שסומכים עליו.`],
 A:{l:['Hold it and say you trust him','להחזיק אותו ולהגיד שסומכים'],s:['A rifle, and a whole man.','רובה, ואדם שלם.'],w:[`You hand it back. He nods once. His shoulders come down for the first time since you met.`,`מוסרים אותו חזרה. הוא מהנהן פעם אחת. הכתפיים שלו יורדות לראשונה מאז הפגישה.`],f:[`Your hands shake, and he sees it.`,`הידיים רועדות, והוא רואה.`],lx:{morale:-4}},
 B:{l:['Refuse. It isn\'t your place','לסרב. זה לא המקום'],s:['Respect is quiet.','כבוד הוא שקט.'],w:[`He shrugs, and puts it away. Respect is quiet.`,`הוא מושך בכתפיים ומניח אותו. כבוד הוא שקט.`],wx:{ammo:1},f:[`He takes it as an insult.`,`הוא לוקח את זה כעלבון.`]}});
story({n:'Dr. Hale',t:['The Notebook','המחברת'],
 x:[`Dr. Hale writes in a notebook she never lets anyone see. Tonight it falls open: equations, and a child's drawing. She says the drawing is the only reason she is still working.`,`ד״ר הייל כותבת במחברת שלעולם לא נותנת לאיש לראות. הלילה היא נפתחת: משוואות, וציור של ילד. היא אומרת שהציור הוא הסיבה היחידה שהיא עדיין עובדת.`],
 A:{l:['Ask about the child','לשאול על הילד'],s:['Some questions are doors.','יש שאלות שהן דלתות.'],w:[`She tells you a name and a date, and you listen for an hour. The equations, she says, are for someone specific.`,`היא מספרת שם ותאריך, ומקשיבים שעה. המשוואות, היא אומרת, הן בשביל מישהו מסוים.`],f:[`She closes the notebook and doesn't speak for a day.`,`היא סוגרת את המחברת ולא מדברת יום.`],lx:{morale:-3}},
 B:{l:['Ask only about the equations','לשאול רק על המשוואות'],s:['Work is also a way to care.','עבודה היא גם דרך לדאוג.'],w:[`She lights up. The next hour is the most useful of the whole road.`,`היא מאירה. השעה הבאה היא השימושית ביותר בכל הדרך.`],wx:{meds:1,morale:3},f:[`She answers in numbers, and none of it is for you.`,`היא עונה במספרים, ושום דבר מזה לא בשבילך.`]}});
story({n:'Sofia',t:['The Trap Line','קו המלכודות'],
 x:[`Sofia checks her traps before every dawn. This morning she asks someone to come with her: there is something she wants to be seen, and something she does not want to see alone.`,`סופיה בודקת את המלכודות שלה לפני כל שחר. הבוקר היא מבקשת שמישהו יבוא איתה: יש משהו שהיא רוצה שיראו, ומשהו שהיא לא רוצה לראות לבד.`],
 A:{l:['Go with her','ללכת איתה'],s:['Two pairs of eyes.','שני זוגות עיניים.'],w:[`The trap line ends at a small stream, and a doe watching from the far bank. Sofia doesn't raise her rifle. You both watch until it leaves.`,`קו המלכודות מסתיים בנחל קטן, ואיילה צופה מהגדה השנייה. סופיה לא מרימה את הרובה. שניכם צופים עד שהיא הולכת.`],f:[`The trap line has been visited by something else.`,`קו המלכודות ביקר בו משהו אחר.`],lx:{hp:-8}},
 B:{l:['Tell her to go alone','להגיד לה ללכת לבד'],s:['She knows the woods.','היא מכירה את היער.'],w:[`She goes alone, and comes back with two rabbits and a nod.`,`היא הולכת לבד, וחוזרת עם שני ארנבים והנהון.`],wx:{food:3},f:[`She comes back empty, and quiet.`,`היא חוזרת ריקה, ושותקת.`]}});
story({n:'Ben',t:['The Door','הדלת'],
 x:[`Ben stands by the door at night, arms folded, even when there is no door. He says it's a habit. He says he was very good at keeping people out. He isn't sure what it's for anymore.`,`בן עומד ליד הדלת בלילה, ידיים שלובות, גם כשאין דלת. הוא אומר שזה הרגל. הוא אומר שהיה טוב מאוד בשמירה על אנשים בחוץ. הוא לא בטוח מה זה בשביל עכשיו.`],
 A:{l:['Sit with him by the doorway','לשבת איתו ליד הפתח'],s:['A long night of nothing.','לילה ארוך של כלום.'],w:[`You talk about nothing until dawn. When the sun comes up, he stands, stretches, and says he's going to sleep, for once.`,`מדברים על כלום עד עלות השחר. כשהשמש עולה, הוא קם, מתמתח ואומר שהולך לישון, לשם שינוי.`],f:[`The night is not quiet.`,`הלילה לא שקט.`],lx:{hp:-8}},
 B:{l:['Give him a job to do','לתת לו משימה'],s:['A purpose is a kind of door.','מטרה היא סוג של דלת.'],w:[`By noon he has built a barricade that would make a general weep.`,`עד הצהריים הוא בנה מחסום שהיה מרגש גנרל.`],wx:{order:2,morale:3},f:[`He does it too well, and nobody can get past.`,`הוא עושה את זה טוב מדי, ואף אחד לא יכול לעבור.`]}});
story({n:'Ines',t:['The Last Shift','המשמרת האחרונה'],
 x:[`Ines never finished her last shift. She talks about it in her sleep: the ward, the handover, a patient in bed six she never checked on. She asks if it would be foolish to go back.`,`אינס מעולם לא סיימה את המשמרת האחרונה שלה. היא מדברת על זה מתוך שינה: המחלקה, ההעברה, מטופל במיטה שש שלא בדקה. היא שואלת אם זה יהיה טיפשי לחזור.`],
 A:{l:['Go back to the hospital with her','לחזור איתה לבית החולים'],s:['Close the chart properly.','לסגור את התיק כמו שצריך.'],w:[`Bed six is empty, and the chart is closed. She signs it herself. It's over.`,`מיטה שש ריקה, והתיק סגור. היא חותמת בעצמה. זה נגמר.`],f:[`The hospital wasn't empty.`,`בית החולים לא היה ריק.`],lx:{hp:-12}},
 B:{l:['Say it would be foolish','להגיד שזה יהיה טיפשי'],s:['Honest, and a little hard.','כנה, וקצת קשה.'],w:[`She says you're right, and it doesn't sound like defeat.`,`היא אומרת שצודקים, וזה לא נשמע כמו תבוסה.`],wx:{meds:1},f:[`She nods and doesn't speak to you for days.`,`היא מהנהנת ולא מדברת איתך ימים.`]}});
story({n:'Omar',t:['The Old Rifle','הרובה הישן'],
 x:[`Omar hunts with a rifle older than he is. Tonight he says his grandfather taught him to shoot, and that it has never missed a deer. He asks if someone would like to learn.`,`עומר צד עם רובה מבוגר ממנו. הלילה הוא אומר שסבו לימד אותו לירות, ושהוא מעולם לא פספס צבי. הוא שואל אם מישהו רוצה ללמוד.`],
 A:{l:['Let him teach you','לתת לו ללמד'],s:['Breath, patience, and silence.','נשימה, סבלנות ושקט.'],w:[`A lesson in breath, patience, and silence. The next morning you stand still for an hour and feel the world go quiet.`,`שיעור בנשימה, בסבלנות ובשקט. למחרת עמדת דומם שעה והרגשת את העולם נעשה שקט.`],wx:{stat:{stealth:1}},f:[`You miss everything, and laugh so loudly you scare off dinner.`,`פספסת הכול, וצחקת כל כך חזק שהבהלת את ארוחת הערב.`],lx:{morale:1}},
 B:{l:['Say you\'ll stick to what you know','להגיד שנשארים עם מה שמכירים'],s:['Polite, and a little proud.','מנומס, וקצת גאה.'],w:[`He nods, and shares his dinner anyway.`,`הוא מהנהן, וחולק את ארוחת הערב שלו בכל זאת.`],wx:{food:3},f:[`He looks disappointed.`,`הוא נראה מאוכזב.`]}});
story({n:'Kim',t:['The Spark','הניצוץ'],
 x:[`Kim has rigged a hand-cranked charger from spare parts. Tonight she offers to power one thing: a lamp, or the memory card from a dead phone. She lets someone choose.`,`קים בנתה מטען ידני מחלקי חילוף. הלילה היא מציעה להפעיל דבר אחד: מנורה, או כרטיס זיכרון מטלפון מת. היא נותנת למישהו לבחור.`],
 A:{l:['The memory card','כרטיס הזיכרון'],s:['Something to remember by.','משהו לזכור בו.'],w:[`Two hundred photographs, a family in a garden. Everyone leans in. Nobody speaks.`,`מאתיים תצלומים, משפחה בגינה. כולם מתכופפים. אף אחד לא מדבר.`],f:[`The card is blank.`,`הכרטיס ריק.`],lx:{morale:-4}},
 B:{l:['The lamp','המנורה'],s:['Light, for an evening.','אור, לערב אחד.'],w:[`Light, for an evening. It is enough.`,`אור, לערב אחד. זה מספיק.`],wx:{hp:6},f:[`The lamp blows, and so does the charger.`,`המנורה נשרפת, וגם המטען.`],lx:{ammo:-1}}});
story({n:'Petra',t:['The Rooftops','הגגות'],
 x:[`Petra runs across rooftops for fun, she says. Tonight she asks someone to try: a gap of two meters, a fall of four floors, and a view worth the trouble.`,`פטרה רצה על גגות לשם הכיף, היא אומרת. הלילה היא מבקשת שמישהו ינסה: פער של שני מטרים, נפילה של ארבע קומות, ונוף ששווה את הטרחה.`],
 A:{l:['Jump the gap','לקפוץ מעל הפער'],s:['For a second, you are nothing.','לשנייה, אתה כלום.'.replace('אתה כלום','כלום')],w:[`You leap. For a second you are nothing. Then you land, and she is laughing.`,`קופצים. לשנייה אתה כלום. אז נוחתים, והיא צוחקת.`.replace('אתה כלום','כלום')],f:[`You don't quite make it.`,`לא בדיוק מצליחים.`],lx:{hp:-14}},
 B:{l:['Take the stairs','לקחת את המדרגות'],s:['Slower, and just as high.','איטי יותר, וגבוה באותה מידה.'],w:[`She sighs and takes the stairs beside you. The view is the same, and somehow quieter.`,`היא נאנחת ויורדת במדרגות לצידך. הנוף זהה, ואיכשהו שקט יותר.`],wx:{morale:3},f:[`She jumps anyway, and you have to watch.`,`היא קופצת בכל זאת, וצריך לצפות.`]}});
story({n:'Joao',t:['The Soup Pot','סיר המרק'],
 x:[`Joao makes the same soup every night from different scraps. Tonight he says it's his mother's. He says it tastes nothing like hers. He asks if someone would taste it and tell him the truth.`,`ז׳ואאו מכין את אותו מרק בכל לילה מפסולת שונה. הלילה הוא אומר שזה המרק של אמו. הוא אומר שטעמו לא דומה בכלל. הוא שואל אם מישהו יטעם ויגיד לו את האמת.`],
 A:{l:['Taste it and tell the truth','לטעום ולהגיד את האמת'],s:['Honesty, with salt.','כנות, עם מלח.'],w:[`It's thin, and needs salt, and you tell him so. He laughs, adds salt, and it's the best soup you've had.`,`הוא דליל וצריך מלח, ואומרים לו. הוא צוחק, מוסיף מלח, וזה המרק הכי טוב שאכלת.`.replace('שאכלת','שנאכל')],f:[`You tell the truth a little too plainly.`,`אומרים את האמת פשוט מדי.`],lx:{morale:-4}},
 B:{l:['Say it is perfect','להגיד שהוא מושלם'],s:['A kind lie.','שקר טוב לב.'],w:[`He glows, and doubles the portions.`,`הוא קורן, ומכפיל את המנות.`],wx:{food:2},f:[`He knows you are lying.`,`הוא יודע שמשקרים.`]}});
story({n:'Rex',t:['The Old Collar','הקולר הישן'],
 x:[`Rex wears a collar with a tag: a phone number, a street, and a name that isn't Rex. Tonight he sits by the fire and looks into the dark, ears up, as if listening for someone.`,`רקס עונד קולר עם תווית: מספר טלפון, רחוב ושם שהוא לא רקס. הלילה הוא יושב ליד האש ומסתכל לחושך, אוזניים זקורות, כאילו מקשיב למישהו.`],
 A:{l:['Follow where he is looking','ללכת לאן שהוא מסתכל'],s:['Dogs know things.','כלבים יודעים דברים.'],w:[`A hundred meters away, a small grave marked with a child's toy. Rex lies beside it for an hour, then walks back with you.`,`מאה מטר משם, קבר קטן שמסומן בצעצוע של ילד. רקס שוכב לידו שעה, ואז חוזר איתך.`],f:[`Where he is looking, something is looking back.`,`במקום שבו הוא מסתכל, משהו מסתכל בחזרה.`],lx:{hp:-8}},
 B:{l:['Call him back to the fire','לקרוא לו חזרה לאש'],s:['Warm, and safe.','חם, ובטוח.'],w:[`He comes, and leans against your knee. That is enough.`,`הוא בא, ונשען על הברך. זה מספיק.`],wx:{hp:3},f:[`He doesn't move, and you sit with the cold.`,`הוא לא זז, וישבים עם הקור.`],lx:{morale:-3}}});
